logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.forink=DEBUG
logging.file.name=/home/ec2-user/forink-back/application.log
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %msg%n