- name: Setup known_hosts and test SSH connection
  run: |
    set -x
    mkdir -p ~/.ssh
    ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
    echo "=== ~/.ssh/known_hosts content ==="
    cat ~/.ssh/known_hosts

    echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa

    ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} SSH 연결 성공!"

